# Generated by Django 3.0.5 on 2020-05-06 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='choice',
            unique_together={('item', 'letter')},
        ),
    ]
