# Generated by Django 3.0.5 on 2020-05-09 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0008_student_user'),
        ('exam', '0003_exam_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='exam.Exam'),
        ),
        migrations.AlterField(
            model_name='session',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='information.Student'),
        ),
    ]
