# Generated by Django 3.0.5 on 2020-04-07 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileusercreationinvitation',
            name='used',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
