# Generated by Django 3.0.5 on 2020-04-07 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profileusercreationinvitation_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profileusercreationinvitation',
            old_name='user',
            new_name='from_who',
        ),
    ]
