# Generated by Django 3.0.5 on 2020-04-08 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profileusercreationpermission_from_who'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileusercreationpermission',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profileusercreationpermission',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
