# Generated by Django 3.0.5 on 2020-04-15 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profileusercreationpermission_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(null=True, upload_to='user_dp/'),
        ),
    ]
