# Generated by Django 3.0.5 on 2020-04-07 10:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0004_auto_20200407_1011'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileUserCreationPermission',
            fields=[
                ('date', models.DateField(auto_now_add=True)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('teacher', 'Teacher')], max_length=7)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('used', models.BooleanField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='information.Department')),
                ('from_who', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='ProfileUserCreationInvitation',
        ),
    ]
