# Generated by Django 3.0.5 on 2020-04-07 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200407_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileusercreationpermission',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
