# Generated by Django 3.0.5 on 2020-04-08 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200407_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id_number',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
