# Generated by Django 3.0.5 on 2020-04-08 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200408_0244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileusercreationpermission',
            name='from_who',
        ),
    ]
