# Generated by Django 3.0.5 on 2020-04-16 05:22

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200415_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='PNG', keep_meta=True, null=True, quality=0, size=[400, 400], upload_to='pics/'),
        ),
    ]
