# Generated by Django 3.0.5 on 2020-05-04 05:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0007_auto_20200504_0545'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0009_auto_20200416_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profileusercreationpermission',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='information.Department'),
        ),
        migrations.AlterField(
            model_name='profileusercreationpermission',
            name='from_who',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to=settings.AUTH_USER_MODEL),
        ),
    ]
