# Generated by Django 3.0.5 on 2020-05-04 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0008_student_user'),
        ('accounts', '0010_auto_20200504_0545'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAccountCreationPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='information.Section')),
            ],
        ),
    ]
