# Generated by Django 3.0.5 on 2020-05-04 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0008_student_user'),
        ('accounts', '0011_studentaccountcreationpermission'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentaccountcreationpermission',
            unique_together={('section', 'code')},
        ),
    ]
