# Generated by Django 3.0.5 on 2020-04-07 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('information', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradingSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('publish', models.BooleanField(default=False)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='information.Department')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='information.Section')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='information.Subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('work_type', models.CharField(choices=[('a', 'Activity'), ('q', 'Quiz'), ('e', 'Examination'), ('p', 'Performace'), ('c', 'Extra')], max_length=1)),
                ('highest_score', models.IntegerField(default=1)),
                ('gsheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='grading.GradingSheet')),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('score', models.IntegerField(default=1)),
                ('gsheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='grading.GradingSheet')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='information.Student')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grading.Work')),
            ],
        ),
    ]
