# Generated by Django 3.0.5 on 2020-04-06 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0001_initial'),
        ('grading', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradingsheet',
            name='section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='information.Section'),
            preserve_default=False,
        ),
    ]
