# Generated by Django 3.0.5 on 2020-04-08 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0003_student_gender'),
        ('accounts', '0003_profileusercreationpermission_gender'),
        ('grading', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradingsheet',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grading_sheets', to='information.Department'),
        ),
        migrations.AlterField(
            model_name='gradingsheet',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grading_sheets', to='information.Section'),
        ),
        migrations.AlterField(
            model_name='gradingsheet',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grading_sheets', to='accounts.Profile'),
        ),
        migrations.AlterField(
            model_name='record',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='information.Student'),
        ),
        migrations.AlterField(
            model_name='record',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='grading.Work'),
        ),
    ]
