# Generated by Django 3.0.5 on 2020-04-08 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0003_student_gender'),
        ('grading', '0002_auto_20200408_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradingsheet',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grading_sheets', to='information.Subject'),
        ),
    ]
