# Generated by Django 3.0.5 on 2020-04-16 08:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('information', '0005_auto_20200416_0832'),
        ('grading', '0004_auto_20200408_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradingsheet',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grading_sheets', to='information.Department'),
        ),
        migrations.AlterField(
            model_name='gradingsheet',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grading_sheets', to='information.Section'),
        ),
        migrations.AlterField(
            model_name='gradingsheet',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grading_sheets', to='information.Subject'),
        ),
        migrations.AlterField(
            model_name='gradingsheet',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grading_sheets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='record',
            name='gsheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='grading.GradingSheet'),
        ),
        migrations.AlterField(
            model_name='record',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='information.Student'),
        ),
        migrations.AlterField(
            model_name='record',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='grading.Work'),
        ),
        migrations.AlterField(
            model_name='work',
            name='gsheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='works', to='grading.GradingSheet'),
        ),
    ]
