# Generated by Django 3.0.5 on 2020-04-20 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0005_auto_20200416_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='gsheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='grading.GradingSheet'),
        ),
        migrations.AlterField(
            model_name='record',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='grading.Work'),
        ),
        migrations.AlterField(
            model_name='work',
            name='gsheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='grading.GradingSheet'),
        ),
    ]
