# Generated by Django 3.0.5 on 2020-04-28 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0010_viewingpermission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewingpermission',
            name='code',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
