# Generated by Django 3.0.5 on 2020-05-10 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0012_auto_20200504_0545'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradingsheet',
            name='has_multiple_choice_exam',
            field=models.BooleanField(default=False),
        ),
    ]
