# Generated by Django 3.0.5 on 2020-05-30 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0014_auto_20200530_0308'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradingsheet',
            name='pt_percent',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='gradingsheet',
            name='qa_percent',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='gradingsheet',
            name='wo_percent',
            field=models.IntegerField(default=20),
        ),
    ]
