# Generated by Django 3.0.5 on 2020-06-01 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0015_auto_20200530_0318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='grading',
            field=models.CharField(choices=[('prelim', 'Prelim'), ('midterm', 'Midterm'), ('finals', 'Finals'), ('1st', 'First Quarter'), ('2nd', 'Second Quarter'), ('3rd', 'Third Quarter'), ('4th', 'Fourth Quarter')], max_length=7),
        ),
        migrations.AlterField(
            model_name='gradingsheet',
            name='grading',
            field=models.CharField(choices=[('prelim', 'Prelim'), ('midterm', 'Midterm'), ('finals', 'Finals'), ('1st', 'First Quarter'), ('2nd', 'Second Quarter'), ('3rd', 'Third Quarter'), ('4th', 'Fourth Quarter')], max_length=7),
        ),
        migrations.AlterField(
            model_name='gradingsheet',
            name='pt_percent',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='gradingsheet',
            name='wo_percent',
            field=models.IntegerField(default=30),
        ),
    ]
