# Generated by Django 3.0.5 on 2020-06-01 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0016_auto_20200601_0651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradingsheet',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
