# Generated by Django 3.0.5 on 2020-06-01 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0017_auto_20200601_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradingsheet',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
