# Generated by Django 3.0.5 on 2020-06-01 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0018_auto_20200601_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalgrade',
            name='sheet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='final_grades', to='grading.GradingSheet'),
        ),
    ]
