# Generated by Django 3.0.5 on 2020-06-02 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0020_auto_20200602_0510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='grading',
            field=models.CharField(choices=[('1st', 'First Quarter'), ('2nd', 'Second Quarter'), ('3rd', 'Third Quarter'), ('4th', 'Fourth Quarter')], max_length=7),
        ),
        migrations.AlterField(
            model_name='gradingsheet',
            name='grading',
            field=models.CharField(choices=[('1st', 'First Quarter'), ('2nd', 'Second Quarter'), ('3rd', 'Third Quarter'), ('4th', 'Fourth Quarter')], max_length=7),
        ),
    ]
