# Generated by Django 3.0.5 on 2020-06-02 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0011_auto_20200512_1224'),
        ('grading', '0021_auto_20200602_0640'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradingSheetGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grading', models.CharField(choices=[('1st', 'First Quarter'), ('2nd', 'Second Quarter'), ('3rd', 'Third Quarter'), ('4th', 'Fourth Quarter')], max_length=7)),
                ('sem', models.CharField(choices=[('1', 'First Semester'), ('2', 'Second Semester')], max_length=1)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='information.Department')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='information.Section')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='information.Subject')),
            ],
        ),
        migrations.AddField(
            model_name='gradingsheet',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='grading_sheets', to='grading.GradingSheetGroup'),
            preserve_default=False,
        ),
    ]
