# Generated by Django 3.0.5 on 2020-06-02 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0022_auto_20200602_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradingsheetgroup',
            name='pt_percent',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='gradingsheetgroup',
            name='qa_percent',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='gradingsheetgroup',
            name='wo_percent',
            field=models.IntegerField(default=30),
        ),
    ]
