# Generated by Django 3.0.5 on 2020-06-03 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0011_auto_20200512_1224'),
        ('grading', '0024_gradingsheetgroup_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gradingsheet',
            name='sem',
        ),
        migrations.RemoveField(
            model_name='gradingsheetgroup',
            name='sem',
        ),
        migrations.AlterUniqueTogether(
            name='card',
            unique_together={('student', 'grading')},
        ),
        migrations.RemoveField(
            model_name='card',
            name='sem',
        ),
    ]
