# Generated by Django 3.0.5 on 2020-04-08 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='information.Section'),
        ),
        migrations.AlterUniqueTogether(
            name='guardianviewingpermission',
            unique_together={('code', 'section')},
        ),
    ]
