# Generated by Django 3.0.5 on 2020-04-16 05:22

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0003_student_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='PNG', keep_meta=True, null=True, quality=0, size=[150, 150], upload_to='pics/'),
        ),
    ]
