# Generated by Django 3.0.5 on 2020-04-16 08:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('information', '0004_auto_20200416_0522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guardianviewingpermission',
            name='from_who',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='guardianviewingpermission',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='information.Section'),
        ),
        migrations.AlterField(
            model_name='section',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sections', to='information.Department'),
        ),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='information.Department'),
        ),
        migrations.AlterField(
            model_name='student',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='information.Section'),
        ),
    ]
