# Generated by Django 3.0.5 on 2020-04-21 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0005_auto_20200416_0832'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GuardianViewingPermission',
        ),
    ]
