# Generated by Django 3.0.5 on 2020-05-04 05:45

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0006_delete_guardianviewingpermission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='PNG', keep_meta=True, null=True, quality=0, size=[400, 400], upload_to='pics/'),
        ),
    ]
