# Generated by Django 3.0.5 on 2020-05-12 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('information', '0009_announcement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='staff',
            field=models.OneToOneField(default=16, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
